// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentTemplate) DeepCopyInto(out *DeploymentTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentTemplate.
func (in *DeploymentTemplate) DeepCopy() *DeploymentTemplate {
	if in == nil {
		return nil
	}
	out := new(DeploymentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeployment) DeepCopyInto(out *KanaryDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeployment.
func (in *KanaryDeployment) DeepCopy() *KanaryDeployment {
	if in == nil {
		return nil
	}
	out := new(KanaryDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KanaryDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentCondition) DeepCopyInto(out *KanaryDeploymentCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentCondition.
func (in *KanaryDeploymentCondition) DeepCopy() *KanaryDeploymentCondition {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentList) DeepCopyInto(out *KanaryDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KanaryDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentList.
func (in *KanaryDeploymentList) DeepCopy() *KanaryDeploymentList {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KanaryDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpec) DeepCopyInto(out *KanaryDeploymentSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.Scale.DeepCopyInto(&out.Scale)
	in.Traffic.DeepCopyInto(&out.Traffic)
	in.Validation.DeepCopyInto(&out.Validation)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpec.
func (in *KanaryDeploymentSpec) DeepCopy() *KanaryDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecScale) DeepCopyInto(out *KanaryDeploymentSpecScale) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(KanaryDeploymentSpecScaleStatic)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecScale.
func (in *KanaryDeploymentSpecScale) DeepCopy() *KanaryDeploymentSpecScale {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecScaleStatic) DeepCopyInto(out *KanaryDeploymentSpecScaleStatic) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecScaleStatic.
func (in *KanaryDeploymentSpecScaleStatic) DeepCopy() *KanaryDeploymentSpecScaleStatic {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecScaleStatic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecTraffic) DeepCopyInto(out *KanaryDeploymentSpecTraffic) {
	*out = *in
	if in.Shadow != nil {
		in, out := &in.Shadow, &out.Shadow
		*out = new(KanaryDeploymentSpecTrafficShadow)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecTraffic.
func (in *KanaryDeploymentSpecTraffic) DeepCopy() *KanaryDeploymentSpecTraffic {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecTrafficShadow) DeepCopyInto(out *KanaryDeploymentSpecTrafficShadow) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecTrafficShadow.
func (in *KanaryDeploymentSpecTrafficShadow) DeepCopy() *KanaryDeploymentSpecTrafficShadow {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecTrafficShadow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecValidation) DeepCopyInto(out *KanaryDeploymentSpecValidation) {
	*out = *in
	if in.ValidationPeriod != nil {
		in, out := &in.ValidationPeriod, &out.ValidationPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Manual != nil {
		in, out := &in.Manual, &out.Manual
		*out = new(KanaryDeploymentSpecValidationManual)
		**out = **in
	}
	if in.LabelWatch != nil {
		in, out := &in.LabelWatch, &out.LabelWatch
		*out = new(KanaryDeploymentSpecValidationLabelWatch)
		(*in).DeepCopyInto(*out)
	}
	if in.PromQL != nil {
		in, out := &in.PromQL, &out.PromQL
		*out = new(KanaryDeploymentSpecValidationPromQL)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecValidation.
func (in *KanaryDeploymentSpecValidation) DeepCopy() *KanaryDeploymentSpecValidation {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecValidationLabelWatch) DeepCopyInto(out *KanaryDeploymentSpecValidationLabelWatch) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentSelector != nil {
		in, out := &in.DeploymentSelector, &out.DeploymentSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecValidationLabelWatch.
func (in *KanaryDeploymentSpecValidationLabelWatch) DeepCopy() *KanaryDeploymentSpecValidationLabelWatch {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecValidationLabelWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecValidationManual) DeepCopyInto(out *KanaryDeploymentSpecValidationManual) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecValidationManual.
func (in *KanaryDeploymentSpecValidationManual) DeepCopy() *KanaryDeploymentSpecValidationManual {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecValidationManual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentSpecValidationPromQL) DeepCopyInto(out *KanaryDeploymentSpecValidationPromQL) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentSpecValidationPromQL.
func (in *KanaryDeploymentSpecValidationPromQL) DeepCopy() *KanaryDeploymentSpecValidationPromQL {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentSpecValidationPromQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KanaryDeploymentStatus) DeepCopyInto(out *KanaryDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]KanaryDeploymentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KanaryDeploymentStatus.
func (in *KanaryDeploymentStatus) DeepCopy() *KanaryDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(KanaryDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
